### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by mikhailmihalkov** [danchitnis/ngspice-sf-mirror#1]
When installing the simulator on Linux, it does not work with the built-in Kicad simulator, and it cannot be installed separately due to library dependencies in the system. The problem is old, maybe there is a solution for Linux?

There is still no solution. This is observed only on Ubuntu if KiCAD is installed via PPA. All software that requires real ngspice (not libraries) becomes broken. Read the thread ra3xdh/qucs_s#333 Read also: https://gitlab.com/kicad/packaging/kicad-ubuntu-builder/ngspice-kicad-pkg/-/issues/4 You can remove ngspice-kicad if you do not need modeling in KiCAD. You can also switch to the version of KiCAD from the Ubuntu system repository. It did not improve this need. I reported this issue to the KiCAD team a year ago, but there is still no response. This was also reported before : https://gitlab.com/kicad/packaging/kicad-ubuntu-builder/ngspice-kicad-pkg/-/issues/2 PPA.

I'm closing this because the problem is in the wrong KiCAD PPA. It can't be solved on the Qucs-S side. It was also reported as ra3xdh/qucs_s#333

**Comment by danchitnis** [comment]
This repository is not monitored by the developers. Please post your issue here:
https://sourceforge.net/projects/ngspice/
